export default {
  lightTheme: {
    PRIMARY_BACKGROUND_COLOR: '#ffffff',
    PRIMARY_BACKGROUND_COLOR_LIGHT: '#f7f7f7',
    SECONDARY_BACKGROUND_COLOR: '#3d3d3d',
    SECONDARY_BACKGROUND_COLOR_LIGHT: '#797979',
    PRIMARY_TEXT_COLOR: '#3d3d3d',
    PRIMARY_TEXT_COLOR_LIGHT: '#797979',
    SECONDARY_TEXT_COLOR: '#ffffff',
    PRIMARY_TEXT_BACKGROUND_COLOR: '#ffffff',
    SECONDARY_TEXT_BACKGROUND_COLOR: '#3d3d3d',
  },
  colorOptions: {
    PRIMARY_COLOR_FAINT: '#E3F2FD',
    PRIMARY_COLOR_LIGHT: '#64B5F6',
    PRIMARY_COLOR: '#2196F3',
    PRIMARY_COLOR_BOLD: '#1565C0',
    PRIMARY_FOREGROUND_COLOR: '#ffffff',
  },
}
